import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { $ } from 'bun'

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const entrypoint = resolve(packageRoot, 'src/plugin.ts')
const outputFile = resolve(packageRoot, '.amp/plugins/background-task.js')

await mkdir(dirname(outputFile), { recursive: true })

await $`bun build ${entrypoint} --target=bun --format=esm --outfile=${outputFile} --external @ampcode/plugin`

const output = await readFile(outputFile, 'utf8')
await writeFile(
	outputFile,
	[
		'// Generated by scripts/build.ts. Do not edit directly.',
		'// Source: src/plugin.ts',
		output,
	].join('\n'),
	'utf8',
)

console.log(`Wrote ${outputFile}`)
